sudo: required
services:
  - docker

before_install:
  - docker build -t billkeller/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run billkeller/react-test npm test -- --coverage

after_success:
  - docker build -t billkeller/multi-client ./client
  - docker build -t billkeller/multi-nginx ./nginx
  - docker build -t billkeller/multi-server ./server
  - docker build -t billkeller/multi-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to dockerhub
  - docker push billkeller/multi-client
  - docker push billkeller/multi-nginx
  - docker push billkeller/multi-server
  - docker push billkeller/multi-worker
